FROM node:18
RUN ln -fs /usr/share/zoneinfo/Europe/Kiev /etc/localtime
   
WORKDIR /node/tms/vue
   
COPY package*.json ./
   
RUN npm install --verbose

RUN umask 002
   
COPY . .

EXPOSE 3011

CMD yarn dev
