FROM node:18

RUN ln -fs /usr/share/zoneinfo/Europe/Kiev /etc/localtime
   
WORKDIR /node/tms/api
   
COPY package*.json ./
   
RUN npm install --verbose
  
COPY . .

CMD npm run start-dev
